### ISSUE TITLE
Distribution has been broken after 1.3: cheetah_cmd.py was not packed

### ISSUE THREAD

**Issue by KonstantinShemyak** [obriencj/python-javatools#100]
`cheetah_cmd.py` is required for `setup.py` to run, but it does not belong to any package. As a result, it is not put in the distribution.

Put it to `extras` module, where it resided sometime in the past.

**Comment by obriencj** [comment]
the extras wasn't really a module, it was just a side directory. I agree that the fix is to move it into a shipped package, but to do so I would rather have it inside the javatools.cheetah namespace. I've created PR #102 which is very similar to yours but just moves things into a different spot.
