### ISSUE TITLE
javatools does not full support java class 52.0 (JDK 8)

### ISSUE THREAD

**Issue by liaoya** [obriencj/python-javatools#24]
When parse the following java class build with the code

File "/usr/lib/python2.7/site-packages/javatools/**init**.py", line 1943, in _unpack_const_item
    raise Unimplemented("unknown constant type %r" % type)
## javatools.Unimplemented: unknown constant type <type 'type'>

import java.time.Instant;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public final class JavaCompatibilityUtil {

  /**
- A comparator that can be used to sort objects into increasing order of
- their toString() length.
  */
  private static final Comparator LAMBDA_COMPARATOR = (Comparator) (Object a, Object b) -> {
    int alen = a.toString().length();
    int blen = b.toString().length();
    if (alen < blen) {
      return -1;
    }
    if (alen > blen) {
      return 1;
    }
    return 0;
  };
  
  private static void functionalAppend(List addto, List addfrom) {
    addfrom.stream().forEach((addfrom1) -> {
      addto.add(addfrom1);
    });
  }
  
  private static void featureTest() {
    Instant inst = Instant.now();
    long time = inst.getEpochSecond();
    time *= 1000000000l; //convert to nanoseconds
    time += inst.getNano(); //the nanoseconds returned by inst.getNano() are the na  
    System.out.print("time="+time+"\n");
  
    Map<String, String> map = new HashMap<>();
    map.put("One", "One");
    map.put("Two", "Two");
    map.put("Tree", "Tree");
    map.put("Four", "Four");
    map.entrySet().stream().filter((entry) -> (entry.getKey().equals("Two"))).forEach((entry) -> {
      System.out.println("is 2 = " + entry.getValue());
    });
  
    String[] atp = {"Rafael Nadal", "Novak Djokovic", "Stanislas Wawrinka", "David Ferrer", "Roger Federer", "Andy Murray", "Tomas Berdych", "Juan Martin Del Potro"};
    List<String> players = Arrays.asList(atp);
    // Using lambda expression and functional operations
    players.forEach(
            (player) -> {
              System.out.print(player + " ; " + map.size());
            }
    );
    // Using double colon operator in Java 8
    players.forEach(System.out::println);
  }
  
  public static void main(String [] args){
    featureTest();
  }

}

**Comment by obriencj** [comment]
I have not yet written java 8 support. Will look into this

**Comment by obriencj** [comment]
I just pushed a rudimentary commit to master that will at least harvest information regarding the constant types used to represent lambdas -- still need real support for comparisons of innerclasses and the like, but it should at least not abend. 

could you try using master from commit 215d87c08b894aa7300229e13de61e05f21234e1 or later?

**Comment by liaoya** [comment]
I', really really sorry to update this issue so late. I download the master branch code and now classinfo can parse Java 1.8 .class file. I thank you for your work very much.

**Comment by obriencj** [comment]
Thanks for verifying!
