### ISSUE TITLE
how to use jardiff

### ISSUE THREAD

**Issue by vah13** [obriencj/python-javatools#25]
hi.
I was downloaded your project and install but help how I can for example compare 2 jar file with jardiff.py?

Thank you

**Comment by vah13** [comment]
I got Traceback (most recent call last):
  File "/tmp/python-javatools/javatools/jardiff.py", line 547, in <module>
    cli(parser, *parser.parse_args(sys.argv))
  File "/tmp/python-javatools/javatools/jardiff.py", line 466, in cli
    return cli_jars_diff(parser, options, left, right)
  File "/tmp/python-javatools/javatools/jardiff.py", line 447, in cli_jars_diff
    delta.check()
  File "/tmp/python-javatools/javatools/change.py", line 362, in check
    self.changed, self.description = self.check_impl()
  File "/tmp/python-javatools/javatools/change.py", line 467, in check_impl
    change.check()
  File "/tmp/python-javatools/javatools/change.py", line 362, in check
    self.changed, self.description = self.check_impl()
  File "/tmp/python-javatools/javatools/jardiff.py", line 320, in check_impl
    with open_zip(self.ldata) as lzip:
  File "/tmp/python-javatools/javatools/ziputils.py", line 327, in open_zip
    return closing(zip_file(filename, mode))
  File "/tmp/python-javatools/javatools/ziputils.py", line 313, in zip_file
    raise Exception("cannot treat as an archive: %r" % fn)
Exception: cannot treat as an archive: '~/Desktop/old/logging.jar'

**Comment by obriencj** [comment]
Whatever version of python you have installed, the zipfile module's is_zipfile method does not see your JAR as a valid archive. Are you sure that it's a valid JAR?

**Comment by vah13** [comment]
https://drive.google.com/file/d/0B7gu5bbuZn2IdWRpUnR4eGU2aEE/view?usp=sharing

**Comment by obriencj** [comment]
Ah hah, try with a full or relative path, without the tilde.

The path ~/Desktop/... isn't being shell-expanded into an actual directory
name, it's being passed along verbatim -- I'll consider that to be a bug in
the CLI.

**Comment by vah13** [comment]
success 
JAR changed
  JAR Contents changed
	Jar Manifest has changed: META-INF/MANIFEST.MF
  	Manifest changed
    	Manifest Main Section has changed

Process finished with exit code 0

and one question
I in 1 -st file have next string 
a = "asdQWE123"

and in second file 
a = "123QWEasd"

jardiff.py don't check it? only manifest ?

**Comment by obriencj** [comment]
What was your invocation? What options did you use? It states "JAR Changed" and "JAR Contents Changed" in your output. If you use one of the report formats, there should be a line indicating that a particular file changed, though it only knows how to do a "smart" delta of manifests and class files. It doesn't try to do text diffing or anything like that.
