### ISSUE TITLE
Signing JARs should support access to private keys via PKCS#11 interface

### ISSUE THREAD

**Issue by KonstantinShemyak** [obriencj/python-javatools#26]
To sign a JAR, python-javatools require private key to be accessible as a readable file in the filesystem. This is rarely a case in security-conscious environments. The most common standard to access private keys is PKCS#11 interface. Python-javatools should support it.

**Comment by obriencj** [comment]
I am unsure if this is appropriately in scope for this project, frankly. This isn't intended to be a full-scale replacement of existing features.

**Comment by KonstantinShemyak** [comment]
Sorry, there has been a mistake: the referenced commit c7339c4 closes KonstantinShemyak#26, not this #26!
But feel free to close this one; PKCS#11 interface is definitely not the first issue in the queue, and I'll recreate it at https://github.com/KonstantinShemyak/python-javatools/issues.
