### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ftomassetti** [obriencj/python-javatools#36]
This project seems amazing to me. Where I can find some examples? I would like to use it to read some Class files (Java 8 format) to read the name and signatures of methods and fields. Is that possible?

**Comment by obriencj** [comment]
It's certainly possible. The "classinfo" CLI in this project should let you do that all from the command line, or you can use it as the basis for how to perform simple unpacking and inspection.

The unpack_classfile function is the simplest starting point to get a JavaClassInfo instance from a .class file you have on disk.

**Comment by waynr** [comment]
I would also be interested in and willing to contribute to API docs for readthedocs.org if that's not already available (didn't see any links in the README).

**Comment by obriencj** [comment]
Documentation is at http://obriencj.preoccupied.net/python-javatools/
It's produced via the Makefile in the docs directory, and pushed to the gh-pages branch of this repository.

**Comment by obriencj** [comment]
added some links in Readme.md ages ago, closing this out
