### ISSUE TITLE
Cut a 1.4 release

### ISSUE THREAD

**Issue by obriencj** [obriencj/python-javatools#54]
Here's a short list of things to do to get a 1.4 out the door

- [x] strip out the pylint, since it's always breaking anyway
- [x] switch to flake8, fix as much as possible
- [x] switch from scripts to entry_points
- [x] clean up some imports, etc (part of this is happening with the flake8 fixes)
- [x] maybe Cheetah can be load-time instead of build-time
- [x] 2.6 vs 2.7 support (Issue #50)
- [ ] test it a bit

**Comment by obriencj** [comment]
@KonstantinShemyak how do you feel about your manifest and signing stuff? Is it fit for a release? Is there anything outstanding you'd like to modify before a 1.4?

**Comment by KonstantinShemyak** [comment]
@obriencj First thing to do is to fix #55. Then, I have collected a number of (unprioritized) issues at https://github.com/KonstantinShemyak/python-javatools/issues . I'll go through them and maybe some of them find their way into 1.4.

**Comment by KonstantinShemyak** [comment]
@obriencj Probably #50 should be handled in one way or another: either denounce Python 2.6 support, or remove all 2.7-only syntax. If asked, I'd vote for the former.

**Comment by obriencj** [comment]
It might be best to just throw 2.6 away. There are certainly a number of
inconveniences that would go away. My issue is that one of the platforms I
initially used this to run deltas was RHEL 6, which is stuck on Python 2.6.
Let me find some time to get a 2.6 devel environ set back up and see if I
can make it pass there. If the number of failures is huge then maybe we
should indeed just move on to 2.7

**Comment by KonstantinShemyak** [comment]
One more bug: https://github.com/KonstantinShemyak/python-javatools/issues/5 . My attempt to fix #39 has failed :(

**Comment by obriencj** [comment]
#55 is fixed, and I've rebased the flake8 branch (which also has the entry_points changes) on master

**Comment by KonstantinShemyak** [comment]
Is there intention to continue maintenance of `gh-pages`?

**Comment by obriencj** [comment]
Yes I'd like to keep that functional, it feeds http://obriencj.preoccupied.net/python-javatools/ which is intended to be the documentation for the project. Feel free to add content to the docs sub-directory if you want to get any documentation updated to mention additional modules.

**Comment by KonstantinShemyak** [comment]
Are there any tests for reports?

I'm investigating KonstantinShemyak#5, it looks like overriding `cmdclass` in `setup.py` causes `install_requires` being ignored ("bug/feature" of setuptools). If pylint would be eliminated, then we can go without overriding `cmdclass` by making reports a setup.py subcommand. But to work on this, I'd like to rely on tests in order not to break them.

**Comment by obriencj** [comment]
pylint is eliminated in the flake8 branch

however, Cheetah is not -- it's still consumed by the cheetah build command.

maybe (maybe) it's okay for us to consider shipping the cheetah templates
as just templates, and doing the compilation at runtime... I'm not sure
that it's really much of a speed-up to ship them pre-compiled into .py
files anyway. The majority of time spent in reporting is definitely in the
actual unpacking and checking tests, not in the report generation. So
lazy-loading/compiling the templates might be a-ok.

I think that the flake8 branch is just about ready. I need to merge master
into flake8 one last time, resolve any conflicts, run tests, etc. Then I'll
ask you to please verify that it looks like it hasn't broken anything for
you. If everything checks out, I'll merge flake8 into master and we can go
forward from there towards also possibly eliminating the Cheetah dep in
setup.py

On Sat, Apr 8, 2017 at 4:27 PM, Konstantin Shemyak <notifications@github.com

**Comment by obriencj** [comment]
merged flake8 into master. Tests all pass, as does ./setup flake8

This moves us to using entry_points for command-line invocation. I noticed some of the jarutil uses sub-command via the first argument. It might be worth investigating argparse as an option at a larger level, to get support for "real" sub-commands.

(I wonder if we couldn't collapse a lot of the javatools CLI into a single entry_point that had a lot of subcommands? Just to avoid polluting the CLI namespace, since "classdiff" etc are very generic names)

This removes the pylint command (which was a huge pain to keep functional anyway). I may want to add the suggested pylint config back for anyone who wants to run it separately...

**Comment by obriencj** [comment]
Updated TODO:
* investigate making cheetah compilation at load-time instead of build-time. That might make it possible to have cheetah be an "optional" dependency, with the features of HTML reporting only enabled when Cheetah is installed, which may be nice for some users.
* Python2.6 support needs to be investigated. If it's just too much of a pain, then maybe we drop it and say 2.7+

**Comment by KonstantinShemyak** [comment]
> merged flake8 into master. Tests all pass, as does ./setup flake8

I do not have any `setup` in the updated `master` (23bd783), neither my `setup.py` knows about flake8?

```
$ python setup.py flake8
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'flake8'
```

**Comment by obriencj** [comment]
Install Flake8 :)

On Sun, Apr 9, 2017 at 1:55 PM, Konstantin Shemyak <notifications@github.com

**Comment by obriencj** [comment]
I delayed the importing of Cheetah from setup.py -- this should allow the install_requires to actually announce that it needs Cheetah before actually trying to import it.

**Comment by KonstantinShemyak** [comment]
On the "test it a bit" point: #68 adds tests for handling options. This [increased line test coverage of the whole project from 48% to 66%](https://coveralls.io/github/KonstantinShemyak/python-javatools) - although it tests mostly "non-core" code.

**Comment by KonstantinShemyak** [comment]
Wow, `argparse` is introduced only in 2.7. This moves support for 2.6 into "too much pain" category...

**Comment by elliottcarlson** [comment]
The current 1.3 release on PyPi does not properly support Python 3 as it fails on the `has_key` in opcodes.py. Is the 1.4 release still planned as it has been 8 months since this issue has been updated?

**Comment by obriencj** [comment]
Eying this up, I haven't heard anymore bug reports on master. I'll see if I can verify that #76 isn't an issue against master. If it's not, I'll tag and push to pypi this weekend.

**Comment by obriencj** [comment]
Just trying to get some more crash-level bugs ironed out.

**Comment by obriencj** [comment]
Tagged as 1.4, and uploaded to pypi as 1.4.0
