### ISSUE TITLE
After rebuilding test data, 3 tests fail

### ISSUE THREAD

**Issue by KonstantinShemyak** [obriencj/python-javatools#66]
After `make clean all` in `tests/data` (copying just some lines of the long output):

```
FAIL: test_const_pool (tests.Sample1Tests)
AssertionError: Tuples differ: ((0, (None, None)), (1, (7, 24... != ((0, (None, None)), (1, (8, 24...

FAIL: test_method_code_name (tests.Sample1Tests)
AssertionError: Tuples differ: ((0, 42, ()), (1, 180, (5,)), ... != ((0, 42, ()), (1, 180, (4,)), ...

FAIL: test_method_code_recent_name (tests.Sample1Tests)
AssertionError: Tuples differ: ((0, 178, (6,)), (3, 176, ())) != ((0, 178, (5,)), (3, 176, ()))
```

Is there any value in giving the user possibility to rebuild the classes? Maybe we should just throw away `Makefile`?

**Comment by obriencj** [comment]
Tests and that Makefile are never shipped, so "the user" is just us in this case. It might be useful to adjust the Makefile with some flags to try and get the rebuilding similar, but no, don't throw it away.

**Comment by obriencj** [comment]
Also, there's a comment about all this at the top of the README.md in tests -- maybe just removing the `clean` is a good idea.
